### ISSUE TITLE
No such property: amazonSESService for class: MyController

### ISSUE THREAD

**Issue by jrtgithub** [agorapulse/grails-aws-sdk-ses#5]
I am pretty new with grails 3 and cannot for the life of me get the Amazon SES to recognize the class. Here is some information about my build. I also couldn't get beta4 to work so I am still using beta3.  I am sure this is something I am just not doing correctly. Any help would be appreciated.

Grails Version: 3.1.1
Groovy Version: 2.4.5
JVM Version: 1.8.0_91

Here is what I am running in MyController

`int statusId = amazonSESService.send(
    'email@email.com',
    'Some subject',
     htmlBody
)`

Here is the error I am getting. When I run the war command the aws ses jar is in the build. 
`No such property: amazonSESService for class: MyController. Stacktrace follows:
groovy.lang.MissingPropertyException: No such property: amazonSESService for class: MyController
    at grails.artefact.gsp.TagLibraryInvoker$Trait$Helper.propertyMissing(TagLibraryInvoker.groovy:121) ~[grails-web-taglib-3.1.1.jar:3.1.1]
    at MyController.index(MyController.groovy:30) ~[main/:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]`

**Comment by benorama** [comment]
That's strange.
Did you add the property in your controller to get the bean injected?

``` groovy
class MyController {

  AmazonSESService amazonSESService

  def index() {
    int statusId = amazonSESService.send( 'email@email.com', 'Some subject', 'Some body' )
    render 'Email sent'
  }

}
```

Also did you run in debug mode with a break point inside your method to check that the bean is correctly injected?

**Comment by jrtgithub** [comment]
I cannot believe I forgot to add the property! However, doing what you said didn't work. Instead, changing the property to def worked. Weird right? 

``` groovy
class MyController {

  def amazonSESService

  def index() {
    int statusId = amazonSESService.send( 'email@email.com', 'Some subject', 'Some body' )
    render 'Email sent'
  }
}
```

**Comment by benorama** [comment]
Great !
